import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { LogoutButton } from "../components/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full border-b bg-white">
          <div className="container py-3 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Link href="/boards" className="btn">Boards</Link>
              <Link href="/tasks" className="btn">Tasks</Link>
            </div>
            <LogoutButton />
          </div>
        </header>
        <main className="container py-6">{children}</main>
      </body>
    </html>
  );
}
